image: python:3.11

stages:
  - lint
  - test
  - doc

cache:
  paths:
    - __pycache__/
    - .pytest_cache/
    - venv/

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

lint_code:
  stage: lint
  script:
    - echo "Запуск линтера..."
    - pylint --fail-under=7 backend/main.py
    - pylint --fail-under=7 backend/application/views.py
    - pylint --fail-under=7 backend/application/schemas.py
    - pylint --fail-under=7 backend/application/utils.py
    - pylint --fail-under=7 backend/application/routes.py
    - pylint --fail-under=7 backend/db/models.py
    - pylint --fail-under=7 backend/db/utils.py

test_code:
  stage: test
  script:
    - echo "Запуск тестов..."
    - pytest

build_docs:
  stage: doc
  script:
    - echo "Генерация документации..."
    - cd docs && .\make html
  artifacts:
    paths:
      - docs/build/html/