FROM python:3.12-slim

WORKDIR /backend

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "backend.application.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]